name = "rio-rita-chat"
main = "src/server/index.ts"
compatibility_date = "2025-04-01"
upload_source_maps = true

[build]
command = "npx postcss public/styles.css -o public/dist/styles.css && npx esbuild src/client/index.tsx --bundle --splitting --format=esm --platform=browser --outdir=public/dist"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

[vars]
GIGAML_AGENT_ID = "agent_template_8c309492-fbc9-414e-a44a-22be19bee601"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Chat"]

[observability]
enabled = true

[dev]
port = 8787
local_protocol = "http"
